application: scrapeplot
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /data
  script: data.py

- url: /update
  script: update.py
  login: admin

